#! /usr/bin/env bash

set -e

DIR="$(dirname "$(readlink -m "$0"/../)")";
build_dir="${DIR}/build_dir"
Dockerfile="${DIR}/Dockerfile.production"

cd $DIR

rm build_dir -rf

mkdir build_dir

files_to_copy="bot.py requirements.txt activityReader.py dev_tools"

for file in $files_to_copy
do
    cp ${file} ${build_dir} -r
done


cat ${Dockerfile} |
    sed -e "s/__UID__/$(id -u)/g" \
        -e "s/__GID__/$(id -g)/g" > ${build_dir}/Dockerfile
