#! /usr/bin/env bash


set -e
target="dev";

# get our local docker network
NET_IF=$(my_public_ip)


DIR="$(dirname "$(readlink -m "$0"/../)")";

parameters=("--rm=true" "--tty=true" "--interactive=true" "--sig-proxy=true"
            "--hostname=activity_reader_${target}"
            "--env=discord_api_token=${discord_api_token}"
            "--env=NET_IF=${NET_IF}")

if [[ "$1" == "--prod" ]];
then
    target="latest";
else
    parameters+=("--volume=${DIR}:/code")
fi

docker run "${parameters[@]}" \
            activity_reader:${target} \
            start
